begin;

create table public.daily_objects (
  id bigint generated by default as identity primary key,
  display_date date not null unique,
  met_object_id integer not null unique check (met_object_id > 0),
  title text not null check (length(trim(title)) > 0),
  artist_display_name text,
  culture text,
  period text,
  dynasty text,
  object_date text,
  medium text,
  department text,
  primary_image text not null,
  primary_image_small text,
  met_object_url text not null,
  summary text,
  why_it_matters text,
  look_closer jsonb not null default '[]'::jsonb
    check (jsonb_typeof(look_closer) = 'array'),
  raw_metadata jsonb,
  created_at timestamptz not null default now()
);

create index daily_objects_display_date_idx on public.daily_objects(display_date desc);
create index daily_objects_met_object_id_idx on public.daily_objects(met_object_id);
alter table public.daily_objects enable row level security;
revoke all on public.daily_objects from anon, authenticated;
grant select on public.daily_objects to anon;
grant all on public.daily_objects to service_role;
grant usage, select on sequence public.daily_objects_id_seq to service_role;
create policy "Public can read daily objects"
  on public.daily_objects for select to anon using (true);

commit;
